name: Zephyrizing
author: Geoff Shannon
tagline: Ruminations on education, programming, and whatever else I feel like talking about.

pygments: true
markdown: kramdown

permalink: pretty

include: [.well-known]
