name: Zephyrizing
author: Geoff Shannon
author_contact: geoffpshannon@gmail.com
tagline: Ruminations on education, programming, and whatever else I feel like talking about.

url: http://www.zephyrizing.net
discourse_url: https://discourse.zephyrizing.net/

pygments: true
markdown: kramdown

permalink: pretty

include: [.well-known]
